name: app-build-action-release
# æ¨é€ Tag æ—¶è§¦å‘
on:
  push:
    tags:
      - "v*"

jobs:
  # æ‰“åŒ… iOS
  build-ios:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: master

      # è®¾ç½® Flutter ç¯å¢ƒ
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # æ‰“å¼€ MAC Desktop æ”¯æŒ
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # æ›´æ–° Flutter çš„ packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # æ‰“åŒ… iOS
      - name: Build IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # åˆ›å»ºæœªç­¾åçš„ IPA
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # ä¸Šä¼  IPA è‡³ Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

  # æ‰“åŒ… Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: master

      # è®¾ç½® Flutter ç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # è®¾ç½® Windows Desktop æ”¯æŒ
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      # æ›´æ–° Flutter çš„ packages
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get

      # æ‰“åŒ… Windows EXE
      - name: Build Windows EXE
        run: |
          cd simple_live_app
          flutter build windows --release

      # æ£€æŸ¥ Windows EXE æ˜¯å¦æˆåŠŸç”Ÿæˆ
      - name: Check if Runner.exe exists
        run: |
          if [ -f "simple_live_app/build/windows/runner/Release/Runner.exe" ]; then
            echo "EXE file exists"
          else
            echo "EXE file not found"
          fi

      # ä¸Šä¼  Windows EXE è‡³ Artifacts
      - name: Upload Windows EXE to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: simple_live_app/build/windows/runner/Release/Runner.exe

      # ç”ŸæˆåŸºäºå½“å‰æ—¶é—´çš„ç‰ˆæœ¬å·
      - name: Generate version number based on current time
        id: generate_version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # ä¸Šä¼ è‡³ Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.generate_version.outputs.version }}"  # è‡ªåŠ¨ç”Ÿæˆç‰ˆæœ¬å·
          body: "Release based on current time"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
            simple_live_app/build/windows/runner/Release/Runner.exe

      # å®Œæˆ
      - run: echo "ğŸ This job's status is ${{ job.status }}."
